server:
  port: 8080

spring:
  application:
    name: migration-api
  profiles:
    active: dev

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging configuration
logging:
  level:
    com.example.migration: INFO
    org.springframework: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.example.migration: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.example.migration: INFO
    org.springframework: WARN